<?php
function tracem_megamenu_add_theme_default_1554556593( $themes ) {
    $themes["default_1554556593"] = array(
        'title' => 'Tracem Menu',
        'container_background_from' => 'rgb(255, 255, 255)',
        'container_background_to' => 'rgb(255, 255, 255)',
        'arrow_up' => 'dash-f343',
        'arrow_down' => 'dash-f347',
        'arrow_left' => 'dash-f341',
        'arrow_right' => 'dash-f345',
        'menu_item_background_hover_from' => 'rgba(255, 255, 255, 0)',
        'menu_item_background_hover_to' => 'rgba(255, 255, 255, 0)',
        'menu_item_link_font_size' => '16px',
        'menu_item_link_height' => '80px',
        'menu_item_link_color' => 'rgb(0, 0, 0)',
        'menu_item_link_weight' => 'bold',
        'menu_item_link_text_transform' => 'capitalize',
        'menu_item_link_color_hover' => 'rgb(0, 0, 0)',
        'menu_item_link_weight_hover' => 'bold',
        'panel_background_from' => 'rgb(18, 18, 18)',
        'panel_background_to' => 'rgb(18, 18, 18)',
        'panel_width' => '700px',
        'panel_inner_width' => '700px',
        'panel_border_color' => 'rgb(18, 18, 18)',
        'panel_border_left' => '1px',
        'panel_border_right' => '1px',
        'panel_border_top' => '1px',
        'panel_border_bottom' => '1px',
        'panel_header_color' => 'rgb(255, 255, 255)',
        'panel_header_border_color' => '#555',
        'panel_padding_left' => '20px',
        'panel_padding_right' => '20px',
        'panel_padding_top' => '20px',
        'panel_padding_bottom' => '20px',
        'panel_widget_padding_left' => '0',
        'panel_widget_padding_right' => '0',
        'panel_widget_padding_top' => '5px',
        'panel_widget_padding_bottom' => '5px',
        'panel_font_size' => '16px',
        'panel_font_color' => '#666',
        'panel_font_family' => 'inherit',
        'panel_second_level_font_color' => 'rgb(213, 213, 213)',
        'panel_second_level_font_color_hover' => 'rgb(255, 255, 255)',
        'panel_second_level_text_transform' => 'capitalize',
        'panel_second_level_font' => 'inherit',
        'panel_second_level_font_size' => '16px',
        'panel_second_level_font_weight' => 'normal',
        'panel_second_level_font_weight_hover' => 'normal',
        'panel_second_level_text_decoration' => 'none',
        'panel_second_level_text_decoration_hover' => 'none',
        'panel_second_level_border_color' => '#555',
        'panel_third_level_font_color' => 'rgb(255, 255, 255)',
        'panel_third_level_font_color_hover' => 'rgb(255, 255, 255)',
        'panel_third_level_font' => 'inherit',
        'panel_third_level_font_size' => '16px',
        'flyout_width' => '200px',
        'flyout_menu_background_from' => 'rgb(18, 18, 18)',
        'flyout_menu_background_to' => 'rgb(18, 18, 18)',
        'flyout_border_color' => 'rgb(18, 18, 18)',
        'flyout_border_left' => '1px',
        'flyout_border_right' => '1px',
        'flyout_border_top' => '1px',
        'flyout_border_bottom' => '1px',
        'flyout_padding_top' => '10px',
        'flyout_padding_bottom' => '10px',
        'flyout_link_padding_left' => '0',
        'flyout_link_padding_right' => '0',
        'flyout_link_padding_top' => '0',
        'flyout_link_padding_bottom' => '0',
        'flyout_background_from' => 'rgba(255, 255, 255, 0)',
        'flyout_background_to' => 'rgba(255, 255, 255, 0)',
        'flyout_background_hover_from' => 'rgba(255, 255, 255, 0)',
        'flyout_background_hover_to' => 'rgba(255, 255, 255, 0)',
        'flyout_link_size' => '16px',
        'flyout_link_color' => 'rgb(213, 213, 213)',
        'flyout_link_color_hover' => 'rgb(255, 255, 255)',
        'flyout_link_family' => 'inherit',
        'z_index' => '9999',
        'toggle_background_from' => '#222',
        'toggle_background_to' => '#222',
        'mobile_background_from' => '#222',
        'mobile_background_to' => '#222',
        'mobile_menu_item_link_font_size' => '14px',
        'mobile_menu_item_link_color' => '#ffffff',
        'mobile_menu_item_link_text_align' => 'left',
        'mobile_menu_item_link_color_hover' => '#ffffff',
        'mobile_menu_item_background_hover_from' => '#333',
        'mobile_menu_item_background_hover_to' => '#333',
        'custom_css' => '/** Push menu onto new line **/ 
#{$wrap} { 
    clear: both; 
}',
    );
    return $themes;
}
add_filter( 'megamenu_themes', 'tracem_megamenu_add_theme_default_1554556593' );